### ISSUE TITLE
cannot query the ingested data

### ISSUE THREAD

**Issue by skarlsson** [mre/kafka-influxdb#27]
I'm trying to configure collectd->kafka->kafka-influxdb->influxdb->grafana

collectd is correctly configured to report to graphite but I wish to use kafka/influxdb instead.

I publish to kafka, pick that up in kafka-influxdb and something shows up in influxdb but I cannot figure out what is wrong since I cannot even query the data. (on the other hand I new to influxdb...)

this is (some of) what the kafka console consumer shows

    f014-520-kafka.internal.machines.smart-sda.smart_powercycles 35 1447706286
    f014-520-kafka.internal.machines.thermal-cooling_device1.gauge 0 1447706286
    f014-520-kafka.internal.machines.thermal-cooling_device3.gauge 0 1447706286
    f014-520-kafka.internal.machines.GenericJMX.gauge-kafka-X-UnderReplicatedPartitions- 0 1447706286

#from collectd.conf

```
<Plugin write_kafka>
   Property "metadata.broker.list" "{{ collectd_kafka_broker_list }}"
<Topic "collectd.graphite">
   Format Graphite
</Topic>
</Plugin>
```

```yaml
#kafka-influxdb.config
kafka:
  host: "f013-520-kafka.internal.machines"
  port: 9092
  topic: "collectd.graphite"
  group: "kafka-influxdb.{{ inventory_hostname }}"
influxdb:
  host: "localhost"
  port: 8086
  user: "root"
  password: "root"
  dbname: "metrics"
  use_ssl: false
  verify_ssl: False
  timeout: 5
  use_udp: False
  retention_policy: "default"
  time_precision: "s"
benchmark: false
buffer_size: 1000
statistics: true
```

#and finally in influx tool
```
use metrics
show measurements;

internal_machines_thermal-cooling_device7_gauge
internal_machines_thermal-cooling_device8_gauge
internal_machines_thermal-cooling_device9_gauge

select * from internal_machines_thermal-cooling_device9_gauge
ERR: error parsing query: found -, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 40
```
do I have to anything else?

any hints appreciated...
